<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>8 Comparing multiple means | A Gentle Introduction to Data Science with R</title>
  <meta name="description" content="8 Comparing multiple means | A Gentle Introduction to Data Science with R" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="8 Comparing multiple means | A Gentle Introduction to Data Science with R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="assets/youreka-logo.png" />
  
  <meta name="github-repo" content="tig3r66/youreka-textbook" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="8 Comparing multiple means | A Gentle Introduction to Data Science with R" />
  
  
  <meta name="twitter:image" content="assets/youreka-logo.png" />

<meta name="author" content="Eddie Guo" />
<meta name="author" content="Youreka Canada Programs Team" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="basic-statistical-tests.html"/>
<link rel="next" href="data-visualization-basics.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="assets/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo"><a href="./"><img src="assets/youreka-logo.png" ></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome to Youreka Canada</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#how-to-use-this-textbook"><i class="fa fa-check"></i>How to use this textbook</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#contributors"><i class="fa fa-check"></i>Contributors</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#credit"><i class="fa fa-check"></i>Credit</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#license"><i class="fa fa-check"></i>License</a></li>
</ul></li>
<li class="part"><span><b>I Prerequisites</b></span></li>
<li class="chapter" data-level="1" data-path="install.html"><a href="install.html"><i class="fa fa-check"></i><b>1</b> Install R and RStudio</a>
<ul>
<li class="chapter" data-level="1.1" data-path="install.html"><a href="install.html#installing-r"><i class="fa fa-check"></i><b>1.1</b> Installing R</a></li>
<li class="chapter" data-level="1.2" data-path="install.html"><a href="install.html#installing-rstudio"><i class="fa fa-check"></i><b>1.2</b> Installing RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="install.html"><a href="install.html#add-on-packages"><i class="fa fa-check"></i><b>1.3</b> Add-on packages</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="basics-of-r-part-1.html"><a href="basics-of-r-part-1.html"><i class="fa fa-check"></i><b>2</b> Basics of R (Part 1)</a>
<ul>
<li class="chapter" data-level="2.1" data-path="basics-of-r-part-1.html"><a href="basics-of-r-part-1.html#objects"><i class="fa fa-check"></i><b>2.1</b> Objects</a></li>
<li class="chapter" data-level="2.2" data-path="basics-of-r-part-1.html"><a href="basics-of-r-part-1.html#function-basics"><i class="fa fa-check"></i><b>2.2</b> Function Basics</a></li>
<li class="chapter" data-level="2.3" data-path="basics-of-r-part-1.html"><a href="basics-of-r-part-1.html#basic-math-operators"><i class="fa fa-check"></i><b>2.3</b> Basic math operators</a></li>
<li class="chapter" data-level="2.4" data-path="basics-of-r-part-1.html"><a href="basics-of-r-part-1.html#conditionals"><i class="fa fa-check"></i><b>2.4</b> Conditionals</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="basics-of-r-part-1.html"><a href="basics-of-r-part-1.html#if-statements"><i class="fa fa-check"></i><b>2.4.1</b> If statements</a></li>
<li class="chapter" data-level="2.4.2" data-path="basics-of-r-part-1.html"><a href="basics-of-r-part-1.html#multiple-ifs-vs-else-if"><i class="fa fa-check"></i><b>2.4.2</b> Multiple “if”s vs “else if”</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="basics-of-r-part-1.html"><a href="basics-of-r-part-1.html#working-directory"><i class="fa fa-check"></i><b>2.5</b> Working directory</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="basics-of-r-part-1.html"><a href="basics-of-r-part-1.html#other-important-things"><i class="fa fa-check"></i><b>2.5.1</b> Other important things</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="basics-of-r-part-2.html"><a href="basics-of-r-part-2.html"><i class="fa fa-check"></i><b>3</b> Basics of R (Part 2)</a>
<ul>
<li class="chapter" data-level="3.1" data-path="basics-of-r-part-2.html"><a href="basics-of-r-part-2.html#data-structures"><i class="fa fa-check"></i><b>3.1</b> Data structures</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="basics-of-r-part-2.html"><a href="basics-of-r-part-2.html#vectors"><i class="fa fa-check"></i><b>3.1.1</b> Vectors</a></li>
<li class="chapter" data-level="3.1.2" data-path="basics-of-r-part-2.html"><a href="basics-of-r-part-2.html#missing-values"><i class="fa fa-check"></i><b>3.1.2</b> Missing values</a></li>
<li class="chapter" data-level="3.1.3" data-path="basics-of-r-part-2.html"><a href="basics-of-r-part-2.html#data-frames"><i class="fa fa-check"></i><b>3.1.3</b> Data frames</a></li>
<li class="chapter" data-level="3.1.4" data-path="basics-of-r-part-2.html"><a href="basics-of-r-part-2.html#external-data"><i class="fa fa-check"></i><b>3.1.4</b> External data</a></li>
<li class="chapter" data-level="3.1.5" data-path="basics-of-r-part-2.html"><a href="basics-of-r-part-2.html#factors"><i class="fa fa-check"></i><b>3.1.5</b> Factors</a></li>
<li class="chapter" data-level="3.1.6" data-path="basics-of-r-part-2.html"><a href="basics-of-r-part-2.html#lists"><i class="fa fa-check"></i><b>3.1.6</b> Lists</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="basics-of-r-part-2.html"><a href="basics-of-r-part-2.html#for-loops"><i class="fa fa-check"></i><b>3.2</b> For loops</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="basics-of-r-part-2.html"><a href="basics-of-r-part-2.html#looping-over-multiple-files"><i class="fa fa-check"></i><b>3.2.1</b> Looping over multiple files</a></li>
<li class="chapter" data-level="3.2.2" data-path="basics-of-r-part-2.html"><a href="basics-of-r-part-2.html#nested-loops-optional"><i class="fa fa-check"></i><b>3.2.2</b> Nested loops (OPTIONAL)</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="basics-of-r-part-2.html"><a href="basics-of-r-part-2.html#functions"><i class="fa fa-check"></i><b>3.3</b> Functions</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="basics-of-r-part-2.html"><a href="basics-of-r-part-2.html#conditionals-within-functions"><i class="fa fa-check"></i><b>3.3.1</b> Conditionals within functions</a></li>
<li class="chapter" data-level="3.3.2" data-path="basics-of-r-part-2.html"><a href="basics-of-r-part-2.html#nested-conditionals"><i class="fa fa-check"></i><b>3.3.2</b> Nested conditionals</a></li>
<li class="chapter" data-level="3.3.3" data-path="basics-of-r-part-2.html"><a href="basics-of-r-part-2.html#function-arguments"><i class="fa fa-check"></i><b>3.3.3</b> Function arguments</a></li>
<li class="chapter" data-level="3.3.4" data-path="basics-of-r-part-2.html"><a href="basics-of-r-part-2.html#combining-functions"><i class="fa fa-check"></i><b>3.3.4</b> Combining functions</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Data Wrangling</b></span></li>
<li class="chapter" data-level="4" data-path="more-data-frames.html"><a href="more-data-frames.html"><i class="fa fa-check"></i><b>4</b> More data frames</a>
<ul>
<li class="chapter" data-level="4.1" data-path="more-data-frames.html"><a href="more-data-frames.html#get-the-gapminder-data"><i class="fa fa-check"></i><b>4.1</b> Get the gapminder data</a></li>
<li class="chapter" data-level="4.2" data-path="more-data-frames.html"><a href="more-data-frames.html#explore-gapminder"><i class="fa fa-check"></i><b>4.2</b> Explore gapminder</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="more-data-frames.html"><a href="more-data-frames.html#importing-and-exporting-data"><i class="fa fa-check"></i><b>4.2.1</b> Importing and exporting data</a></li>
<li class="chapter" data-level="4.2.2" data-path="more-data-frames.html"><a href="more-data-frames.html#exploring-variables-in-a-data-frame"><i class="fa fa-check"></i><b>4.2.2</b> Exploring variables in a data frame</a></li>
<li class="chapter" data-level="4.2.3" data-path="more-data-frames.html"><a href="more-data-frames.html#data-frame-summary"><i class="fa fa-check"></i><b>4.2.3</b> Data frame summary</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="more-data-frames.html"><a href="more-data-frames.html#data-frames-with-dplyr"><i class="fa fa-check"></i><b>4.3</b> Data frames with dplyr</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="more-data-frames.html"><a href="more-data-frames.html#subsetting-data"><i class="fa fa-check"></i><b>4.3.1</b> Subsetting data</a></li>
<li class="chapter" data-level="4.3.2" data-path="more-data-frames.html"><a href="more-data-frames.html#filter-rows-with-filter"><i class="fa fa-check"></i><b>4.3.2</b> Filter rows with <code>filter()</code></a></li>
<li class="chapter" data-level="4.3.3" data-path="more-data-frames.html"><a href="more-data-frames.html#pipe-operator"><i class="fa fa-check"></i><b>4.3.3</b> Pipe operator <code>%&gt;%</code></a></li>
<li class="chapter" data-level="4.3.4" data-path="more-data-frames.html"><a href="more-data-frames.html#select-columns-with-select"><i class="fa fa-check"></i><b>4.3.4</b> Select Columns with <code>select()</code></a></li>
<li class="chapter" data-level="4.3.5" data-path="more-data-frames.html"><a href="more-data-frames.html#pure-predictable-pipeable-optional"><i class="fa fa-check"></i><b>4.3.5</b> Pure, predictable, pipeable (OPTIONAL)</a></li>
<li class="chapter" data-level="4.3.6" data-path="more-data-frames.html"><a href="more-data-frames.html#additional-resources"><i class="fa fa-check"></i><b>4.3.6</b> Additional resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="more-dplyr.html"><a href="more-dplyr.html"><i class="fa fa-check"></i><b>5</b> More dplyr</a>
<ul>
<li class="chapter" data-level="5.1" data-path="more-dplyr.html"><a href="more-dplyr.html#review-and-preparation"><i class="fa fa-check"></i><b>5.1</b> Review and preparation</a></li>
<li class="chapter" data-level="5.2" data-path="more-dplyr.html"><a href="more-dplyr.html#use-mutate-to-add-new-variables"><i class="fa fa-check"></i><b>5.2</b> Use mutate() to add new variables</a></li>
<li class="chapter" data-level="5.3" data-path="more-dplyr.html"><a href="more-dplyr.html#use-arrange-to-row-order-data"><i class="fa fa-check"></i><b>5.3</b> Use arrange() to row-order data</a></li>
<li class="chapter" data-level="5.4" data-path="more-dplyr.html"><a href="more-dplyr.html#use-rename-to-rename-variables"><i class="fa fa-check"></i><b>5.4</b> Use rename() to rename variables</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="more-dplyr.html"><a href="more-dplyr.html#use-select-to-rename-and-reposition-variables"><i class="fa fa-check"></i><b>5.4.1</b> Use select() to rename and reposition variables</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="more-dplyr.html"><a href="more-dplyr.html#perform-tasks-on-subsets-with-group_by"><i class="fa fa-check"></i><b>5.5</b> Perform tasks on subsets with <code>group_by()</code></a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="more-dplyr.html"><a href="more-dplyr.html#counting"><i class="fa fa-check"></i><b>5.5.1</b> Counting</a></li>
<li class="chapter" data-level="5.5.2" data-path="more-dplyr.html"><a href="more-dplyr.html#general-summarization"><i class="fa fa-check"></i><b>5.5.2</b> General summarization</a></li>
<li class="chapter" data-level="5.5.3" data-path="more-dplyr.html"><a href="more-dplyr.html#computing-with-group-wise-summaries"><i class="fa fa-check"></i><b>5.5.3</b> Computing with group-wise summaries</a></li>
<li class="chapter" data-level="5.5.4" data-path="more-dplyr.html"><a href="more-dplyr.html#window-functions-optional"><i class="fa fa-check"></i><b>5.5.4</b> Window functions (OPTIONAL)</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="more-dplyr.html"><a href="more-dplyr.html#introduction-to-visualization-optional"><i class="fa fa-check"></i><b>5.6</b> Introduction to visualization (OPTIONAL)</a></li>
<li class="chapter" data-level="5.7" data-path="more-dplyr.html"><a href="more-dplyr.html#comprehensive-practice"><i class="fa fa-check"></i><b>5.7</b> Comprehensive practice</a></li>
<li class="chapter" data-level="5.8" data-path="more-dplyr.html"><a href="more-dplyr.html#data-wrangling-summary"><i class="fa fa-check"></i><b>5.8</b> Data wrangling summary</a></li>
</ul></li>
<li class="part"><span><b>III Statistics</b></span></li>
<li class="chapter" data-level="6" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html"><i class="fa fa-check"></i><b>6</b> Central limit theorem</a>
<ul>
<li class="chapter" data-level="6.1" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#clt-for-means"><i class="fa fa-check"></i><b>6.1</b> CLT for means</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#clt-part-1"><i class="fa fa-check"></i><b>6.1.1</b> CLT Part 1</a></li>
<li class="chapter" data-level="6.1.2" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#clt-part-2"><i class="fa fa-check"></i><b>6.1.2</b> CLT Part 2</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#clt-for-proportions"><i class="fa fa-check"></i><b>6.2</b> CLT for proportions</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html"><i class="fa fa-check"></i><b>7</b> Basic statistical tests</a>
<ul>
<li class="chapter" data-level="7.1" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#getting-ready"><i class="fa fa-check"></i><b>7.1</b> Getting ready</a></li>
<li class="chapter" data-level="7.2" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#students-t-test"><i class="fa fa-check"></i><b>7.2</b> Student’s t-test</a></li>
<li class="chapter" data-level="7.3" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#chi-squared-test"><i class="fa fa-check"></i><b>7.3</b> Chi-squared test</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#chi2-test-for-goodness-of-fit"><i class="fa fa-check"></i><b>7.3.1</b> <span class="math inline">\(\chi^2\)</span> test for goodness-of-fit</a></li>
<li class="chapter" data-level="7.3.2" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#chi2-test-for-independence"><i class="fa fa-check"></i><b>7.3.2</b> <span class="math inline">\(\chi^2\)</span> test for independence</a></li>
<li class="chapter" data-level="7.3.3" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#chi2-test-for-homogeneity"><i class="fa fa-check"></i><b>7.3.3</b> <span class="math inline">\(\chi^2\)</span> test for homogeneity</a></li>
<li class="chapter" data-level="7.3.4" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#fishers-exact-test-optional"><i class="fa fa-check"></i><b>7.3.4</b> Fisher’s exact test (OPTIONAL)</a></li>
<li class="chapter" data-level="7.3.5" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#comparison-of-proportions-optional"><i class="fa fa-check"></i><b>7.3.5</b> Comparison of proportions (OPTIONAL)</a></li>
<li class="chapter" data-level="7.3.6" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#contingency-tables"><i class="fa fa-check"></i><b>7.3.6</b> Contingency tables</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#visualizing-data-distributions-optional"><i class="fa fa-check"></i><b>7.4</b> Visualizing data distributions (OPTIONAL)</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="comparing-multiple-means.html"><a href="comparing-multiple-means.html"><i class="fa fa-check"></i><b>8</b> Comparing multiple means</a>
<ul>
<li class="chapter" data-level="8.1" data-path="comparing-multiple-means.html"><a href="comparing-multiple-means.html#loading-packages"><i class="fa fa-check"></i><b>8.1</b> Loading packages</a></li>
<li class="chapter" data-level="8.2" data-path="comparing-multiple-means.html"><a href="comparing-multiple-means.html#merging-datasets"><i class="fa fa-check"></i><b>8.2</b> Merging datasets</a></li>
<li class="chapter" data-level="8.3" data-path="comparing-multiple-means.html"><a href="comparing-multiple-means.html#one-way-anova"><i class="fa fa-check"></i><b>8.3</b> One-way ANOVA</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="comparing-multiple-means.html"><a href="comparing-multiple-means.html#the-iris-dataset"><i class="fa fa-check"></i><b>8.3.1</b> The iris dataset</a></li>
<li class="chapter" data-level="8.3.2" data-path="comparing-multiple-means.html"><a href="comparing-multiple-means.html#non-parametric-alternatives-to-anova"><i class="fa fa-check"></i><b>8.3.2</b> Non-parametric alternatives to ANOVA</a></li>
<li class="chapter" data-level="8.3.3" data-path="comparing-multiple-means.html"><a href="comparing-multiple-means.html#two-way-anova"><i class="fa fa-check"></i><b>8.3.3</b> Two-way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="comparing-multiple-means.html"><a href="comparing-multiple-means.html#linear-regression"><i class="fa fa-check"></i><b>8.4</b> Linear regression</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="comparing-multiple-means.html"><a href="comparing-multiple-means.html#basic-concepts"><i class="fa fa-check"></i><b>8.4.1</b> Basic concepts</a></li>
<li class="chapter" data-level="8.4.2" data-path="comparing-multiple-means.html"><a href="comparing-multiple-means.html#pearson-correlation"><i class="fa fa-check"></i><b>8.4.2</b> Pearson correlation</a></li>
<li class="chapter" data-level="8.4.3" data-path="comparing-multiple-means.html"><a href="comparing-multiple-means.html#spearman-correlation"><i class="fa fa-check"></i><b>8.4.3</b> Spearman correlation</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IV Data Visualization</b></span></li>
<li class="chapter" data-level="9" data-path="data-visualization-basics.html"><a href="data-visualization-basics.html"><i class="fa fa-check"></i><b>9</b> Data visualization basics</a>
<ul>
<li class="chapter" data-level="9.1" data-path="data-visualization-basics.html"><a href="data-visualization-basics.html#a-graphing-template"><i class="fa fa-check"></i><b>9.1</b> A graphing template</a></li>
<li class="chapter" data-level="9.2" data-path="data-visualization-basics.html"><a href="data-visualization-basics.html#scatter-plot"><i class="fa fa-check"></i><b>9.2</b> Scatter plot</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="data-visualization-basics.html"><a href="data-visualization-basics.html#trend-lines"><i class="fa fa-check"></i><b>9.2.1</b> Trend lines</a></li>
<li class="chapter" data-level="9.2.2" data-path="data-visualization-basics.html"><a href="data-visualization-basics.html#facets"><i class="fa fa-check"></i><b>9.2.2</b> Facets</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="data-visualization-basics.html"><a href="data-visualization-basics.html#aesthetic-mappings"><i class="fa fa-check"></i><b>9.3</b> Aesthetic mappings</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="getting-publication-ready.html"><a href="getting-publication-ready.html"><i class="fa fa-check"></i><b>10</b> Getting publication-ready</a>
<ul>
<li class="chapter" data-level="10.1" data-path="getting-publication-ready.html"><a href="getting-publication-ready.html#line-plot"><i class="fa fa-check"></i><b>10.1</b> Line plot</a></li>
<li class="chapter" data-level="10.2" data-path="getting-publication-ready.html"><a href="getting-publication-ready.html#bar-plot"><i class="fa fa-check"></i><b>10.2</b> Bar plot</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="getting-publication-ready.html"><a href="getting-publication-ready.html#basics"><i class="fa fa-check"></i><b>10.2.1</b> Basics</a></li>
<li class="chapter" data-level="10.2.2" data-path="getting-publication-ready.html"><a href="getting-publication-ready.html#plotting-significance-optional"><i class="fa fa-check"></i><b>10.2.2</b> Plotting significance (OPTIONAL)</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="getting-publication-ready.html"><a href="getting-publication-ready.html#box-plot"><i class="fa fa-check"></i><b>10.3</b> Box plot</a></li>
<li class="chapter" data-level="10.4" data-path="getting-publication-ready.html"><a href="getting-publication-ready.html#histogram-and-density-plot"><i class="fa fa-check"></i><b>10.4</b> Histogram and density plot</a></li>
<li class="chapter" data-level="10.5" data-path="getting-publication-ready.html"><a href="getting-publication-ready.html#assembly-of-multiple-figures-optional"><i class="fa fa-check"></i><b>10.5</b> Assembly of multiple figures (OPTIONAL)</a></li>
<li class="chapter" data-level="10.6" data-path="getting-publication-ready.html"><a href="getting-publication-ready.html#extras-optional"><i class="fa fa-check"></i><b>10.6</b> Extras (OPTIONAL)</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="getting-publication-ready.html"><a href="getting-publication-ready.html#choropleth"><i class="fa fa-check"></i><b>10.6.1</b> Choropleth</a></li>
<li class="chapter" data-level="10.6.2" data-path="getting-publication-ready.html"><a href="getting-publication-ready.html#animations"><i class="fa fa-check"></i><b>10.6.2</b> Animations</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="getting-publication-ready.html"><a href="getting-publication-ready.html#additional-resources-1"><i class="fa fa-check"></i><b>10.7</b> Additional resources</a></li>
</ul></li>
<li class="divider"></li>
<li><center>
  <a rel="license" href="./index.html#license">
    License: CC-BY-SA<br>
    <i class = "fab fa-creative-commons fa-2x"></i>
    <i class = "fab fa-creative-commons-by fa-2x"></i>
    <i class = "fab fa-creative-commons-sa fa-2x"></i>
  </a>
</li></center>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Gentle Introduction to Data Science with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="comparing-multiple-means" class="section level1" number="8">
<h1><span class="header-section-number">8</span> Comparing multiple means</h1>
<p>Throughout this lab, we will provide a pipeline to help you wrangle data, perform statistical analyses, and (perhaps most importantly) visualize data in R. Here, we will learn how to compare the means using parametric tests and medians using non-parametric tests of multiple groups.</p>
<div id="loading-packages" class="section level2" number="8.1">
<h2><span class="header-section-number">8.1</span> Loading packages</h2>
<p>Let’s load the usual packages.</p>
<div class="sourceCode" id="cb435"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb435-1"><a href="comparing-multiple-means.html#cb435-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gapminder)</span>
<span id="cb435-2"><a href="comparing-multiple-means.html#cb435-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)       <span class="co"># car stands for Companion to Applied Regression</span></span>
<span id="cb435-3"><a href="comparing-multiple-means.html#cb435-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
</div>
<div id="merging-datasets" class="section level2" number="8.2">
<h2><span class="header-section-number">8.2</span> Merging datasets</h2>
<p>In this section, we will learn how to merge datasets. We will use something called <a href="https://www.eiu.com/topic/democracy-index">democracy index (democracy score)</a> and convert it into categorical data. As the name suggests, democracy index measures the degree of democracy of a country on a scale from 0 to 10, with higher scores being correlated with greater democracy. In our dataset, however, the scale is from -10 to 10. This data set has been pre-cleaned and made available on <a href="https://www.gapminder.org/data/">gapminder</a>. Alternatively, download the file by <a href="./data/07_multi-compare/democracy_score_use_as_color.csv">clicking here</a>.</p>
<p>Let’s load our dataset.</p>
<div class="sourceCode" id="cb436"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb436-1"><a href="comparing-multiple-means.html#cb436-1" aria-hidden="true" tabindex="-1"></a>democracy.raw <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">&quot;data/07_multi-compare/democracy_score_use_as_color.csv&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>The first thing you should do with new data is explore it. Since the output is quite large, we’ll only show the first row, but you should definitely take a deeper look.</p>
<div class="sourceCode" id="cb437"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb437-1"><a href="comparing-multiple-means.html#cb437-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(democracy.raw, <span class="at">n=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>##       country X1800 X1801 X1802 X1803 X1804 X1805 X1806 X1807 X1808 X1809 X1810
## 1 Afghanistan    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6
##   X1811 X1812 X1813 X1814 X1815 X1816 X1817 X1818 X1819 X1820 X1821 X1822 X1823
## 1    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6
##   X1824 X1825 X1826 X1827 X1828 X1829 X1830 X1831 X1832 X1833 X1834 X1835 X1836
## 1    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6
##   X1837 X1838 X1839 X1840 X1841 X1842 X1843 X1844 X1845 X1846 X1847 X1848 X1849
## 1    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6
##   X1850 X1851 X1852 X1853 X1854 X1855 X1856 X1857 X1858 X1859 X1860 X1861 X1862
## 1    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6
##   X1863 X1864 X1865 X1866 X1867 X1868 X1869 X1870 X1871 X1872 X1873 X1874 X1875
## 1    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6
##   X1876 X1877 X1878 X1879 X1880 X1881 X1882 X1883 X1884 X1885 X1886 X1887 X1888
## 1    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6
##   X1889 X1890 X1891 X1892 X1893 X1894 X1895 X1896 X1897 X1898 X1899 X1900 X1901
## 1    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6
##   X1902 X1903 X1904 X1905 X1906 X1907 X1908 X1909 X1910 X1911 X1912 X1913 X1914
## 1    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6
##   X1915 X1916 X1917 X1918 X1919 X1920 X1921 X1922 X1923 X1924 X1925 X1926 X1927
## 1    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6    -6
##   X1928 X1929 X1930 X1931 X1932 X1933 X1934 X1935 X1936 X1937 X1938 X1939 X1940
## 1    -6    -6    -6    -6    -6    -6    -6    -8    -8    -8    -8    -8    -8
##   X1941 X1942 X1943 X1944 X1945 X1946 X1947 X1948 X1949 X1950 X1951 X1952 X1953
## 1    -8    -8    -8    -8   -10   -10   -10   -10   -10   -10   -10   -10   -10
##   X1954 X1955 X1956 X1957 X1958 X1959 X1960 X1961 X1962 X1963 X1964 X1965 X1966
## 1   -10   -10   -10   -10   -10   -10   -10   -10   -10   -10    -7    -7    -7
##   X1967 X1968 X1969 X1970 X1971 X1972 X1973 X1974 X1975 X1976 X1977 X1978 X1979
## 1    -7    -7    -7    -7    -7    -7    -7    -7    -7    -7    -7     0   -10
##   X1980 X1981 X1982 X1983 X1984 X1985 X1986 X1987 X1988 X1989 X1990 X1991 X1992
## 1   -10   -10   -10   -10   -10   -10   -10   -10   -10    -8    -8    -8     0
##   X1993 X1994 X1995 X1996 X1997 X1998 X1999 X2000 X2001 X2002 X2003 X2004 X2005
## 1     0     0     0    -7    -7    -7    -7    -7    NA    NA    NA    NA    NA
##   X2006 X2007 X2008 X2009 X2010 X2011
## 1    NA    NA    NA    NA    NA    NA</code></pre>
<p>Don’t forget about <code>str()</code> and <code>summary()</code>!</p>
<div class="sourceCode" id="cb439"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb439-1"><a href="comparing-multiple-means.html#cb439-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(democracy.raw)</span>
<span id="cb439-2"><a href="comparing-multiple-means.html#cb439-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(democracy.raw)</span></code></pre></div>
<p>As you can see, there is a lot of missing data (denoted by NA). NA values are often problematic for analyses, so we would like to either remove them or impute (estimate) them. In our case, let’s get rid of the rws with missing data for the year 2007 (the <code>X2007</code> column).</p>
<div class="sourceCode" id="cb440"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb440-1"><a href="comparing-multiple-means.html#cb440-1" aria-hidden="true" tabindex="-1"></a>dem07 <span class="ot">&lt;-</span> democracy.raw <span class="sc">%&gt;%</span></span>
<span id="cb440-2"><a href="comparing-multiple-means.html#cb440-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(country, X2007) <span class="sc">%&gt;%</span>  <span class="co"># choose</span></span>
<span id="cb440-3"><a href="comparing-multiple-means.html#cb440-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(X2007))       <span class="co"># selecting all non-NA rows</span></span></code></pre></div>
<p>Here, <code>is.na()</code> will return TRUE for missing data. Recall that <code>!</code> is the NOT logical operator (i.e., <code>!TRUE</code> is equivalent to <code>FALSE</code> and vice versa. It follows that <code>!is.na()</code> returns true for non-empty data.</p>
<p>Let’s take a looks at how the democracy score is distributed. Here, I’d like to treat each democracy score as a factor.</p>
<div class="sourceCode" id="cb441"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb441-1"><a href="comparing-multiple-means.html#cb441-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dem07, <span class="fu">aes</span>(<span class="fu">as.factor</span>(X2007))) <span class="sc">+</span></span>
<span id="cb441-2"><a href="comparing-multiple-means.html#cb441-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-188-1.png" width="672" /></p>
<p>Before we do anything, let’s look at some potentially interesting counts. First, we’ll look at two ways to count “low-level” countries. To do so, we will arbitrarily define any democracy score <span class="math inline">\(\leq\)</span> -3 as low-level. Now, we will count the number of countries in each group.</p>
<div class="sourceCode" id="cb442"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb442-1"><a href="comparing-multiple-means.html#cb442-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(dem07[dem07<span class="sc">$</span>X2007 <span class="sc">&lt;=</span> <span class="sc">-</span><span class="dv">3</span>,])  <span class="co"># base R</span></span></code></pre></div>
<pre><code>## [1] 39</code></pre>
<div class="sourceCode" id="cb444"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb444-1"><a href="comparing-multiple-means.html#cb444-1" aria-hidden="true" tabindex="-1"></a>dem07 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(X2007 <span class="sc">&lt;=</span> <span class="sc">-</span><span class="dv">3</span>) <span class="sc">%&gt;%</span> <span class="fu">nrow</span>()  <span class="co"># with dplyr pipe operator</span></span></code></pre></div>
<pre><code>## [1] 39</code></pre>
<p>Let’s define medium-level countries as having a democracy score betwen -2 and 5 inclusive.</p>
<div class="sourceCode" id="cb446"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb446-1"><a href="comparing-multiple-means.html#cb446-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(dem07[dem07<span class="sc">$</span>X2007 <span class="sc">&gt;=</span> <span class="sc">-</span><span class="dv">2</span> <span class="sc">&amp;</span> dem07<span class="sc">$</span>X2007 <span class="sc">&lt;=</span> <span class="dv">5</span>,])  <span class="co"># base R</span></span></code></pre></div>
<pre><code>## [1] 32</code></pre>
<div class="sourceCode" id="cb448"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb448-1"><a href="comparing-multiple-means.html#cb448-1" aria-hidden="true" tabindex="-1"></a>dem07 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(X2007 <span class="sc">&gt;=</span> <span class="sc">-</span><span class="dv">2</span> <span class="sc">&amp;</span> X2007 <span class="sc">&lt;=</span> <span class="dv">5</span>) <span class="sc">%&gt;%</span> <span class="fu">nrow</span>()  <span class="co"># with dplyr pipe operator</span></span></code></pre></div>
<pre><code>## [1] 32</code></pre>
<p><strong>Exercise:</strong> count the number of high-level countries using both base R and dplyr. High-level countries will be defined as those with democracy score greater or equal to 6.</p>
<p>Now let’s actually assign a new categorical variable to each country (row) using the <code>cut()</code> function. Let’s call the new row <code>demLev</code> (our shorthand for democracy level).</p>
<div class="sourceCode" id="cb450"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb450-1"><a href="comparing-multiple-means.html#cb450-1" aria-hidden="true" tabindex="-1"></a>tempDemLev <span class="ot">&lt;-</span> <span class="fu">cut</span>(dem07<span class="sc">$</span>X2007,</span>
<span id="cb450-2"><a href="comparing-multiple-means.html#cb450-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="sc">-</span><span class="fl">2.5</span>, <span class="fl">4.5</span>, <span class="cn">Inf</span>),</span>
<span id="cb450-3"><a href="comparing-multiple-means.html#cb450-3" aria-hidden="true" tabindex="-1"></a>        <span class="fu">c</span>(<span class="st">&quot;LowDem&quot;</span>, <span class="st">&quot;MidDem&quot;</span>, <span class="st">&quot;HighDem&quot;</span>))</span>
<span id="cb450-4"><a href="comparing-multiple-means.html#cb450-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb450-5"><a href="comparing-multiple-means.html#cb450-5" aria-hidden="true" tabindex="-1"></a>dem07<span class="sc">$</span>demLev <span class="ot">&lt;-</span> tempDemLev  <span class="co"># base R method</span></span>
<span id="cb450-6"><a href="comparing-multiple-means.html#cb450-6" aria-hidden="true" tabindex="-1"></a><span class="co"># dem07 &lt;- dem07 %&gt;% mutate(demLev = tempDemLev)  # dplyr method</span></span>
<span id="cb450-7"><a href="comparing-multiple-means.html#cb450-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dem07)</span></code></pre></div>
<pre><code>##     country X2007  demLev
## 1   Albania     9 HighDem
## 2   Algeria     2  MidDem
## 3    Angola    -2  MidDem
## 4 Argentina     8 HighDem
## 5   Armenia     5 HighDem
## 6 Australia    10 HighDem</code></pre>
<p><strong>Note:</strong> The first argument for <code>cut()</code> takes a vector, the second takes the vector for cutoff thresholds, and the third are names of the bins defined by the cutoffs.</p>
<p>We can now merge this new data with gapminder. The main idea of merging is to add the new variables as columns. The identifier of our observations will be <code>country</code>. Since we are taking data from different sources, a given country might exist in one data frame but not the other. Furthermore, the two data sets might use different names for the countries. Before merging, let’s check the data we want to merge. Note that <code>str_detect()</code> finds all instances where a particular string is in a column.</p>
<div class="sourceCode" id="cb452"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb452-1"><a href="comparing-multiple-means.html#cb452-1" aria-hidden="true" tabindex="-1"></a><span class="co"># let&#39;s check how they name Korea</span></span>
<span id="cb452-2"><a href="comparing-multiple-means.html#cb452-2" aria-hidden="true" tabindex="-1"></a>dem07 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">str_detect</span>(country, <span class="st">&#39;Korea&#39;</span>))</span></code></pre></div>
<pre><code>##       country X2007  demLev
## 1 North Korea   -10  LowDem
## 2 South Korea     8 HighDem</code></pre>
<div class="sourceCode" id="cb454"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb454-1"><a href="comparing-multiple-means.html#cb454-1" aria-hidden="true" tabindex="-1"></a>gapminder <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">str_detect</span>(country, <span class="st">&#39;Korea&#39;</span>))</span></code></pre></div>
<pre><code>## # A tibble: 24 x 6
##    country          continent  year lifeExp      pop gdpPercap
##    &lt;fct&gt;            &lt;fct&gt;     &lt;int&gt;   &lt;dbl&gt;    &lt;int&gt;     &lt;dbl&gt;
##  1 Korea, Dem. Rep. Asia       1952    50.1  8865488     1088.
##  2 Korea, Dem. Rep. Asia       1957    54.1  9411381     1571.
##  3 Korea, Dem. Rep. Asia       1962    56.7 10917494     1622.
##  4 Korea, Dem. Rep. Asia       1967    59.9 12617009     2144.
##  5 Korea, Dem. Rep. Asia       1972    64.0 14781241     3702.
##  6 Korea, Dem. Rep. Asia       1977    67.2 16325320     4106.
##  7 Korea, Dem. Rep. Asia       1982    69.1 17647518     4107.
##  8 Korea, Dem. Rep. Asia       1987    70.6 19067554     4106.
##  9 Korea, Dem. Rep. Asia       1992    70.0 20711375     3726.
## 10 Korea, Dem. Rep. Asia       1997    67.7 21585105     1691.
## # … with 14 more rows</code></pre>
<p>Now that we have a clear idea of which each looks like, we need to determine the potential differences between them. For example, you can’t merge <code>'Korea, Dem. Rep.'</code> with <code>'Korea'</code> since the two strings are not exactly equal.</p>
<div class="sourceCode" id="cb456"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb456-1"><a href="comparing-multiple-means.html#cb456-1" aria-hidden="true" tabindex="-1"></a><span class="co"># setdiff() finds the differences between values in each dataset</span></span>
<span id="cb456-2"><a href="comparing-multiple-means.html#cb456-2" aria-hidden="true" tabindex="-1"></a><span class="co"># unique() ensures that there are no duplicate values</span></span>
<span id="cb456-3"><a href="comparing-multiple-means.html#cb456-3" aria-hidden="true" tabindex="-1"></a><span class="fu">setdiff</span>(<span class="fu">unique</span>(dem07<span class="sc">$</span>country), <span class="fu">unique</span>(gapminder<span class="sc">$</span>country))</span></code></pre></div>
<pre><code>##  [1] &quot;Armenia&quot;              &quot;Azerbaijan&quot;           &quot;Belarus&quot;             
##  [4] &quot;Bhutan&quot;               &quot;Cape Verde&quot;           &quot;Cyprus&quot;              
##  [7] &quot;Estonia&quot;              &quot;Fiji&quot;                 &quot;Georgia&quot;             
## [10] &quot;Guyana&quot;               &quot;Kazakhstan&quot;           &quot;Kyrgyz Republic&quot;     
## [13] &quot;Lao&quot;                  &quot;Latvia&quot;               &quot;Lithuania&quot;           
## [16] &quot;Moldova&quot;              &quot;North Korea&quot;          &quot;North Macedonia&quot;     
## [19] &quot;Papua New Guinea&quot;     &quot;Qatar&quot;                &quot;Russia&quot;              
## [22] &quot;Solomon Islands&quot;      &quot;South Korea&quot;          &quot;Suriname&quot;            
## [25] &quot;Tajikistan&quot;           &quot;Timor-Leste&quot;          &quot;Turkmenistan&quot;        
## [28] &quot;Ukraine&quot;              &quot;United Arab Emirates&quot; &quot;Uzbekistan&quot;          
## [31] &quot;Yemen&quot;</code></pre>
<div class="sourceCode" id="cb458"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb458-1"><a href="comparing-multiple-means.html#cb458-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setdiff</span>(<span class="fu">unique</span>(gapminder<span class="sc">$</span>country), <span class="fu">unique</span>(dem07<span class="sc">$</span>country))</span></code></pre></div>
<pre><code>##  [1] &quot;Afghanistan&quot;            &quot;Bosnia and Herzegovina&quot; &quot;Hong Kong, China&quot;      
##  [4] &quot;Iceland&quot;                &quot;Korea, Dem. Rep.&quot;       &quot;Korea, Rep.&quot;           
##  [7] &quot;Puerto Rico&quot;            &quot;Reunion&quot;                &quot;Sao Tome and Principe&quot; 
## [10] &quot;Taiwan&quot;                 &quot;West Bank and Gaza&quot;     &quot;Yemen, Rep.&quot;</code></pre>
<p>It looks like we need to change “South Korea” to “Korea, Rep.” and “Yemen” to “Yemen, Rep.” We can do this using the factor recode function: <code>fct_recode()</code></p>
<div class="sourceCode" id="cb460"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb460-1"><a href="comparing-multiple-means.html#cb460-1" aria-hidden="true" tabindex="-1"></a>dem07 <span class="ot">&lt;-</span> dem07 <span class="sc">%&gt;%</span></span>
<span id="cb460-2"><a href="comparing-multiple-means.html#cb460-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">country =</span> <span class="fu">fct_recode</span>(country,</span>
<span id="cb460-3"><a href="comparing-multiple-means.html#cb460-3" aria-hidden="true" tabindex="-1"></a>                              <span class="st">&#39;Korea, Rep.&#39;</span> <span class="ot">=</span> <span class="st">&#39;South Korea&#39;</span>,</span>
<span id="cb460-4"><a href="comparing-multiple-means.html#cb460-4" aria-hidden="true" tabindex="-1"></a>                              <span class="st">&#39;Yemen, Rep.&#39;</span> <span class="ot">=</span> <span class="st">&#39;Yemen&#39;</span>))</span></code></pre></div>
<p>Finally, let’s can merge the two data frames using a left join. There are many types of joins (right join, inner join, etc.), and you can check them out <a href="https://dplyr.tidyverse.org/reference/join.html">here</a>.</p>
<div class="sourceCode" id="cb461"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb461-1"><a href="comparing-multiple-means.html#cb461-1" aria-hidden="true" tabindex="-1"></a><span class="co"># need to filter out missing data!</span></span>
<span id="cb461-2"><a href="comparing-multiple-means.html#cb461-2" aria-hidden="true" tabindex="-1"></a>my_gap <span class="ot">&lt;-</span> gapminder <span class="sc">%&gt;%</span></span>
<span id="cb461-3"><a href="comparing-multiple-means.html#cb461-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(dem07, <span class="at">by =</span> <span class="st">&quot;country&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb461-4"><a href="comparing-multiple-means.html#cb461-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(demLev)) <span class="sc">%&gt;%</span></span>
<span id="cb461-5"><a href="comparing-multiple-means.html#cb461-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(lifeExp))</span>
<span id="cb461-6"><a href="comparing-multiple-means.html#cb461-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb461-7"><a href="comparing-multiple-means.html#cb461-7" aria-hidden="true" tabindex="-1"></a><span class="co"># let&#39;s see what the data looks like now</span></span>
<span id="cb461-8"><a href="comparing-multiple-means.html#cb461-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(my_gap)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 8
##   country continent  year lifeExp     pop gdpPercap X2007 demLev 
##   &lt;fct&gt;   &lt;fct&gt;     &lt;int&gt;   &lt;dbl&gt;   &lt;int&gt;     &lt;dbl&gt; &lt;int&gt; &lt;fct&gt;  
## 1 Albania Europe     1952    55.2 1282697     1601.     9 HighDem
## 2 Albania Europe     1957    59.3 1476505     1942.     9 HighDem
## 3 Albania Europe     1962    64.8 1728137     2313.     9 HighDem
## 4 Albania Europe     1967    66.2 1984060     2760.     9 HighDem
## 5 Albania Europe     1972    67.7 2263554     3313.     9 HighDem
## 6 Albania Europe     1977    68.9 2509048     3533.     9 HighDem</code></pre>
<p>Please note that <code>demLev</code> was based on the score of 2007. We don’t do that here, but you could also include the levels based on the scores from different years.</p>
</div>
<div id="one-way-anova" class="section level2" number="8.3">
<h2><span class="header-section-number">8.3</span> One-way ANOVA</h2>
<div id="the-iris-dataset" class="section level3" number="8.3.1">
<h3><span class="header-section-number">8.3.1</span> The iris dataset</h3>
<p>The iris dataset contains information about three species of flowers: setosa, veriscolor, and virginia. Iris is a built-in dataset, meaning we can call it without reading it in.</p>
<ul>
<li><code>iris$Species</code> refers to one column in <code>iris</code>. That is, the column with the name of the species (setosa, versicolor, or virginica).</li>
<li>We can see how many rows and columns are in a <code>data.frame</code> with the <code>dim</code> command. <code>dim(iris)</code> prints out the number of rows (150) and the number of columns (5):</li>
</ul>
<div class="sourceCode" id="cb463"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb463-1"><a href="comparing-multiple-means.html#cb463-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(iris)</span></code></pre></div>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          4.9         3.0          1.4         0.2  setosa
## 3          4.7         3.2          1.3         0.2  setosa
## 4          4.6         3.1          1.5         0.2  setosa
## 5          5.0         3.6          1.4         0.2  setosa
## 6          5.4         3.9          1.7         0.4  setosa</code></pre>
<div class="sourceCode" id="cb465"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb465-1"><a href="comparing-multiple-means.html#cb465-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(iris)</span></code></pre></div>
<pre><code>##   Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
##  Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
##  1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
##  Median :5.800   Median :3.000   Median :4.350   Median :1.300  
##  Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
##  3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
##  Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
##        Species  
##  setosa    :50  
##  versicolor:50  
##  virginica :50  
##                 
##                 
## </code></pre>
<p>Analysis of Variance (ANOVA) allows us to test whether there are differences in the mean between multiple samples. The question we will address is:</p>
<p><strong>Are there differences in average sepal width among the three species?</strong></p>
<p>To run an ANOVA, we need to check if</p>
<ol style="list-style-type: decimal">
<li>The variance is is equal for <em>each group</em>, and</li>
<li>The data distributes normally within <em>each group</em>.</li>
</ol>
<p>Let’s address the first point.</p>
<div class="sourceCode" id="cb467"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb467-1"><a href="comparing-multiple-means.html#cb467-1" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(Sepal.Width <span class="sc">~</span> Species, <span class="at">data =</span> iris)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##        Df F value Pr(&gt;F)
## group   2  0.5902 0.5555
##       147</code></pre>
<p>A p-value of 0.5555 suggested that the variances are not significantly different. This means we should proceed with a parametric test like ANOVA (otherwise, use the Kruskal-Wallis test). Keep in mind we haven’t yet checked the normality. We will do it after running ANOVA.</p>
<p>We start by building an analysis of variance model with the <code>aov()</code> function:</p>
<p>In this case, we pass <em>two</em> arguments to the <code>aov()</code> function:</p>
<ol style="list-style-type: decimal">
<li>For the <code>formula</code> parameter, we pass <code>Sepal.Width ~ Species</code>. This format is used throughout R for describing relationships we are testing. The format is <code>y ~ x</code>, where the response variables (e.g. <code>y</code>) are to the left of the tilde (~) and the predictor variables (e.g. <code>x</code>) are to the right of the tilde. In this example, we are asking if petal length is significantly different among the three species.</li>
<li>We also need to tell R where to find the <code>Sepal.Width</code> and <code>Species</code> data, so we pass the variable name of the <code>iris data.frame</code> to the <code>data</code> parameter.</li>
</ol>
<p>But we want to store the model, not just print it to the screen, so we use the assignment operator <code>&lt;-</code> to store the product of the <code>aov</code> function in a variable of our choice</p>
<div class="sourceCode" id="cb469"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb469-1"><a href="comparing-multiple-means.html#cb469-1" aria-hidden="true" tabindex="-1"></a>Sepal.Width.aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="at">formula =</span> Sepal.Width <span class="sc">~</span> Species, <span class="at">data =</span> iris)</span></code></pre></div>
<p>Notice how when we execute this command, nothing printed in the console. This is because we instead sent the output of the <code>aov</code> call to a variable. If you just type the variable name, you will see the familiar output from the <code>aov</code> function:</p>
<div class="sourceCode" id="cb470"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb470-1"><a href="comparing-multiple-means.html#cb470-1" aria-hidden="true" tabindex="-1"></a>Sepal.Width.aov</span></code></pre></div>
<pre><code>## Call:
##    aov(formula = Sepal.Width ~ Species, data = iris)
## 
## Terms:
##                  Species Residuals
## Sum of Squares  11.34493  16.96200
## Deg. of Freedom        2       147
## 
## Residual standard error: 0.3396877
## Estimated effects may be unbalanced</code></pre>
<p>To see the results of the ANOVA, we call the <code>summary()</code> function:</p>
<div class="sourceCode" id="cb472"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb472-1"><a href="comparing-multiple-means.html#cb472-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="at">object =</span> Sepal.Width.aov)</span></code></pre></div>
<pre><code>##              Df Sum Sq Mean Sq F value Pr(&gt;F)    
## Species       2  11.35   5.672   49.16 &lt;2e-16 ***
## Residuals   147  16.96   0.115                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The species <em>do</em> have significantly different sepal width (P &lt; 0.001). However, ANOVA does not tell us <em>which</em> species are different. We can run a <em>post hoc</em> test to assess <em>how</em> the species are different. A Tukey test comparing means would be one option. We will do the Tukey test after determining normality.</p>
<p>Now, let’s take a look at the normality. First, we will plot the diagnostic figures.</p>
<div class="sourceCode" id="cb474"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb474-1"><a href="comparing-multiple-means.html#cb474-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Sepal.Width.aov)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-201-1.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-201-2.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-201-3.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-201-4.png" width="672" /></p>
<p>Most importantly, the dots in Q-Q plot (upper right) should align with the line pretty well. This figure is acceptable. If the dots deviate from the line too much, the data would not be considered normal. If you still perform the ANOVA, you should view your results critically (or ignore them, at worst).</p>
<p>Please do not include such diagnostic figures in the main text of your manuscripts. This might qualify for a supplementary figure at most.</p>
<p>Although we’ve also examined residuals with the QQ plot, we can also use a formal test:</p>
<div class="sourceCode" id="cb475"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb475-1"><a href="comparing-multiple-means.html#cb475-1" aria-hidden="true" tabindex="-1"></a>residuals_Sepal_Width <span class="ot">&lt;-</span> <span class="fu">residuals</span>(<span class="at">object =</span> Sepal.Width.aov)</span>
<span id="cb475-2"><a href="comparing-multiple-means.html#cb475-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="at">x =</span> residuals_Sepal_Width)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuals_Sepal_Width
## W = 0.98948, p-value = 0.323</code></pre>
<p>A p-value of 0.323 suggested that the assumption of normality is reasonable.</p>
<p>Recall that a residual is an “error” in result. More specifically, a residual is the difference of a given data point from the mean (<span class="math inline">\(r = x - \mu\)</span>).</p>
<p>So far, we have demonstrated</p>
<ol style="list-style-type: decimal">
<li>Normality in distribution.</li>
<li>Homogeneity variance, and</li>
</ol>
<p>These two justified our choice for one-way ANOVA. The result of ANOVA also indicated that at least one species of the 3 has significantly different sepal width from others. Which one?</p>
<p>To do this, we need to run “Post-Hoc” test. Let’s do Tukey Honest Significant Differences (HSD). The nice thing is that <code>TukeyHSD()</code> can directly take the result of ANOVA as the argument.</p>
<div class="sourceCode" id="cb477"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb477-1"><a href="comparing-multiple-means.html#cb477-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(Sepal.Width.aov)</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = Sepal.Width ~ Species, data = iris)
## 
## $Species
##                        diff         lwr        upr     p adj
## versicolor-setosa    -0.658 -0.81885528 -0.4971447 0.0000000
## virginica-setosa     -0.454 -0.61485528 -0.2931447 0.0000000
## virginica-versicolor  0.204  0.04314472  0.3648553 0.0087802</code></pre>
<p>The difference between every pair are significant (<span class="math inline">\(p &lt; 0.05\)</span>).</p>
</div>
<div id="non-parametric-alternatives-to-anova" class="section level3" number="8.3.2">
<h3><span class="header-section-number">8.3.2</span> Non-parametric alternatives to ANOVA</h3>
<p>In reality, your data usually wouldn’t be as perfect as above.</p>
<p>In case of a non-normal sample, there are two ways to address the problem:</p>
<ol style="list-style-type: decimal">
<li>Apply appropriate <a href="https://fmwww.bc.edu/repec/bocode/t/transint.html">data transformations techniques</a>, or</li>
<li>Use a non-parametric test</li>
</ol>
<p>I highly recommend you to explore the tricks of data transformation. If you can rescue it back to normal distribution, parametric tests usually can allow you to do more powerful analysis.</p>
<p>If you have exhausted your attempts to data transformation, you may then use non-parametric tests. A note for <a href="http://www.biostathandbook.com/kruskalwallis.html">Kruskal-Wallis H-test</a>.</p>
<p>When your data doesn’t satisfy the normality or equal variance assumption, ANOVA does not strictly apply. However, one-way ANOVA is not very sensitive to deviations from normality. Kruskal-Wallis doesn’t assume normality, but it does assume same distribution (equal variance). If your data do not meet either assumption, you would want to use Welch’s One-way Test. Now, let’s get back to gapminder data.</p>
<p>Let’s add another categorical variable calle <code>Income_Level</code>. This time we will split by the quartiles.</p>
<div class="sourceCode" id="cb479"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb479-1"><a href="comparing-multiple-means.html#cb479-1" aria-hidden="true" tabindex="-1"></a>dat<span class="fl">.1952</span> <span class="ot">&lt;-</span> my_gap <span class="sc">%&gt;%</span> <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">1952</span>)</span>
<span id="cb479-2"><a href="comparing-multiple-means.html#cb479-2" aria-hidden="true" tabindex="-1"></a>border_1952 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(dat<span class="fl">.1952</span><span class="sc">$</span>gdpPercap, <span class="fu">c</span>(.<span class="dv">25</span>, .<span class="dv">50</span>, .<span class="dv">75</span>))</span>
<span id="cb479-3"><a href="comparing-multiple-means.html#cb479-3" aria-hidden="true" tabindex="-1"></a>dat<span class="fl">.1952</span><span class="sc">$</span>Income_Level_1952 <span class="ot">&lt;-</span> <span class="fu">cut</span>(dat<span class="fl">.1952</span><span class="sc">$</span>gdpPercap,</span>
<span id="cb479-4"><a href="comparing-multiple-means.html#cb479-4" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">c</span>(<span class="dv">0</span>, border_1952[<span class="dv">1</span>],</span>
<span id="cb479-5"><a href="comparing-multiple-means.html#cb479-5" aria-hidden="true" tabindex="-1"></a>                                    border_1952[<span class="dv">2</span>], border_1952[<span class="dv">3</span>], <span class="cn">Inf</span>),</span>
<span id="cb479-6"><a href="comparing-multiple-means.html#cb479-6" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">c</span>(<span class="st">&#39;Low&#39;</span>, <span class="st">&#39;Low Middle&#39;</span>, <span class="st">&#39;High Middle&#39;</span>, <span class="st">&#39;High&#39;</span>))</span>
<span id="cb479-7"><a href="comparing-multiple-means.html#cb479-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat<span class="fl">.1952</span>)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 9
##   country continent  year lifeExp    pop gdpPercap X2007 demLev Income_Level_19…
##   &lt;fct&gt;   &lt;fct&gt;     &lt;int&gt;   &lt;dbl&gt;  &lt;int&gt;     &lt;dbl&gt; &lt;int&gt; &lt;fct&gt;  &lt;fct&gt;           
## 1 Albania Europe     1952    55.2 1.28e6     1601.     9 HighD… Low Middle      
## 2 Algeria Africa     1952    43.1 9.28e6     2449.     2 MidDem High Middle     
## 3 Angola  Africa     1952    30.0 4.23e6     3521.    -2 MidDem High Middle     
## 4 Argent… Americas   1952    62.5 1.79e7     5911.     8 HighD… High            
## 5 Austra… Oceania    1952    69.1 8.69e6    10040.    10 HighD… High            
## 6 Austria Europe     1952    66.8 6.93e6     6137.    10 HighD… High</code></pre>
<div class="sourceCode" id="cb481"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb481-1"><a href="comparing-multiple-means.html#cb481-1" aria-hidden="true" tabindex="-1"></a>dat<span class="fl">.2007</span> <span class="ot">&lt;-</span> my_gap <span class="sc">%&gt;%</span> <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2007</span>)</span>
<span id="cb481-2"><a href="comparing-multiple-means.html#cb481-2" aria-hidden="true" tabindex="-1"></a>border_2007 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(dat<span class="fl">.2007</span><span class="sc">$</span>gdpPercap, <span class="fu">c</span>(.<span class="dv">25</span>, .<span class="dv">50</span>, .<span class="dv">75</span>))</span>
<span id="cb481-3"><a href="comparing-multiple-means.html#cb481-3" aria-hidden="true" tabindex="-1"></a>dat<span class="fl">.2007</span><span class="sc">$</span>Income_Level_2007 <span class="ot">&lt;-</span> <span class="fu">cut</span>(dat<span class="fl">.2007</span><span class="sc">$</span>gdpPercap,</span>
<span id="cb481-4"><a href="comparing-multiple-means.html#cb481-4" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">c</span>(<span class="dv">0</span>, border_2007[<span class="dv">1</span>],</span>
<span id="cb481-5"><a href="comparing-multiple-means.html#cb481-5" aria-hidden="true" tabindex="-1"></a>                                    border_2007[<span class="dv">2</span>], border_2007[<span class="dv">3</span>], <span class="cn">Inf</span>),</span>
<span id="cb481-6"><a href="comparing-multiple-means.html#cb481-6" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">c</span>(<span class="st">&#39;Low&#39;</span>, <span class="st">&#39;Low Middle&#39;</span>, <span class="st">&#39;High Middle&#39;</span>, <span class="st">&#39;High&#39;</span>))</span>
<span id="cb481-7"><a href="comparing-multiple-means.html#cb481-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat<span class="fl">.2007</span>)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 9
##   country continent  year lifeExp    pop gdpPercap X2007 demLev Income_Level_20…
##   &lt;fct&gt;   &lt;fct&gt;     &lt;int&gt;   &lt;dbl&gt;  &lt;int&gt;     &lt;dbl&gt; &lt;int&gt; &lt;fct&gt;  &lt;fct&gt;           
## 1 Albania Europe     2007    76.4 3.60e6     5937.     9 HighD… Low Middle      
## 2 Algeria Africa     2007    72.3 3.33e7     6223.     2 MidDem High Middle     
## 3 Angola  Africa     2007    42.7 1.24e7     4797.    -2 MidDem Low Middle      
## 4 Argent… Americas   2007    75.3 4.03e7    12779.     8 HighD… High Middle     
## 5 Austra… Oceania    2007    81.2 2.04e7    34435.    10 HighD… High            
## 6 Austria Europe     2007    79.8 8.20e6    36126.    10 HighD… High</code></pre>
<p>For now, let’s focus on the data of in 1952.</p>
<div class="sourceCode" id="cb483"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb483-1"><a href="comparing-multiple-means.html#cb483-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> dat<span class="fl">.1952</span>, <span class="fu">aes</span>(<span class="at">x =</span> Income_Level_1952, <span class="at">y =</span> lifeExp)) <span class="sc">+</span></span>
<span id="cb483-2"><a href="comparing-multiple-means.html#cb483-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb483-3"><a href="comparing-multiple-means.html#cb483-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-205-1.png" width="672" /></p>
<p>We can also visualize life expectancy for each democracy level:</p>
<div class="sourceCode" id="cb484"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb484-1"><a href="comparing-multiple-means.html#cb484-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> dat<span class="fl">.1952</span>, <span class="fu">aes</span>(<span class="at">x =</span> demLev, <span class="at">y =</span> lifeExp)) <span class="sc">+</span></span>
<span id="cb484-2"><a href="comparing-multiple-means.html#cb484-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb484-3"><a href="comparing-multiple-means.html#cb484-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-206-1.png" width="672" /></p>
<p>Let’s check the variance.</p>
<div class="sourceCode" id="cb485"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb485-1"><a href="comparing-multiple-means.html#cb485-1" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(lifeExp <span class="sc">~</span> Income_Level_1952, <span class="at">data =</span> dat<span class="fl">.1952</span>)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##        Df F value   Pr(&gt;F)   
## group   3  4.2319 0.006881 **
##       128                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>A p-value of 0.0047 suggested that the variances are significantly different. Therefore, we shoud not run ANOVA or Kruskal-Wallis. Let’s run Welch’s one-way test.</p>
<div class="sourceCode" id="cb487"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb487-1"><a href="comparing-multiple-means.html#cb487-1" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">oneway.test</span>(lifeExp <span class="sc">~</span> Income_Level_1952, <span class="at">data =</span> dat<span class="fl">.1952</span>)</span>
<span id="cb487-2"><a href="comparing-multiple-means.html#cb487-2" aria-hidden="true" tabindex="-1"></a>result</span></code></pre></div>
<pre><code>## 
##  One-way analysis of means (not assuming equal variances)
## 
## data:  lifeExp and Income_Level_1952
## F = 63.15, num df = 3.000, denom df = 68.584, p-value &lt; 2.2e-16</code></pre>
<p>A p-value of 2.2e-16 suggested that at least one category of <code>Income_Level_1952</code> had values of <code>lifeExp</code> that are significantly different from others. Let’s run a Post-Hoc test to find out.</p>
<p>Since we are running a non-parametric test, the appropriate test would be Games-Howell post-hoc test. Unfortunately, R does not have a built-in function for Games-Howell. Let’s define a function to do this task.</p>
<p><strong>Note</strong>: you don’t need to know how the code below works.</p>
<div class="sourceCode" id="cb489"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb489-1"><a href="comparing-multiple-means.html#cb489-1" aria-hidden="true" tabindex="-1"></a>games.howell <span class="ot">&lt;-</span> <span class="cf">function</span>(grp, obs) {</span>
<span id="cb489-2"><a href="comparing-multiple-means.html#cb489-2" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Create combinations</span></span>
<span id="cb489-3"><a href="comparing-multiple-means.html#cb489-3" aria-hidden="true" tabindex="-1"></a>  combs <span class="ot">&lt;-</span> <span class="fu">combn</span>(<span class="fu">unique</span>(grp), <span class="dv">2</span>)</span>
<span id="cb489-4"><a href="comparing-multiple-means.html#cb489-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb489-5"><a href="comparing-multiple-means.html#cb489-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Statistics that will be used throughout the calculations:</span></span>
<span id="cb489-6"><a href="comparing-multiple-means.html#cb489-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># n = sample size of each group</span></span>
<span id="cb489-7"><a href="comparing-multiple-means.html#cb489-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># groups = number of groups in data</span></span>
<span id="cb489-8"><a href="comparing-multiple-means.html#cb489-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Mean = means of each group sample</span></span>
<span id="cb489-9"><a href="comparing-multiple-means.html#cb489-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># std = variance of each group sample</span></span>
<span id="cb489-10"><a href="comparing-multiple-means.html#cb489-10" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">tapply</span>(obs, grp, length)</span>
<span id="cb489-11"><a href="comparing-multiple-means.html#cb489-11" aria-hidden="true" tabindex="-1"></a>  groups <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">tapply</span>(obs, grp, length))</span>
<span id="cb489-12"><a href="comparing-multiple-means.html#cb489-12" aria-hidden="true" tabindex="-1"></a>  Mean <span class="ot">&lt;-</span> <span class="fu">tapply</span>(obs, grp, mean)</span>
<span id="cb489-13"><a href="comparing-multiple-means.html#cb489-13" aria-hidden="true" tabindex="-1"></a>  std <span class="ot">&lt;-</span> <span class="fu">tapply</span>(obs, grp, var)</span>
<span id="cb489-14"><a href="comparing-multiple-means.html#cb489-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb489-15"><a href="comparing-multiple-means.html#cb489-15" aria-hidden="true" tabindex="-1"></a>  statistics <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(combs), <span class="cf">function</span>(x) {</span>
<span id="cb489-16"><a href="comparing-multiple-means.html#cb489-16" aria-hidden="true" tabindex="-1"></a>    mean.diff <span class="ot">&lt;-</span> Mean[combs[<span class="dv">2</span>,x]] <span class="sc">-</span> Mean[combs[<span class="dv">1</span>,x]]</span>
<span id="cb489-17"><a href="comparing-multiple-means.html#cb489-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># t-values</span></span>
<span id="cb489-18"><a href="comparing-multiple-means.html#cb489-18" aria-hidden="true" tabindex="-1"></a>    t <span class="ot">&lt;-</span> <span class="fu">abs</span>(Mean[combs[<span class="dv">1</span>,x]] <span class="sc">-</span> Mean[combs[<span class="dv">2</span>,x]]) <span class="sc">/</span> <span class="fu">sqrt</span>((std[combs[<span class="dv">1</span>,x]] <span class="sc">/</span> n[combs[<span class="dv">1</span>,x]]) <span class="sc">+</span> (std[combs[<span class="dv">2</span>,x]] <span class="sc">/</span> n[combs[<span class="dv">2</span>,x]]))</span>
<span id="cb489-19"><a href="comparing-multiple-means.html#cb489-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Degrees of Freedom</span></span>
<span id="cb489-20"><a href="comparing-multiple-means.html#cb489-20" aria-hidden="true" tabindex="-1"></a>    df <span class="ot">&lt;-</span> (std[combs[<span class="dv">1</span>,x]] <span class="sc">/</span> n[combs[<span class="dv">1</span>,x]] <span class="sc">+</span> std[combs[<span class="dv">2</span>,x]] <span class="sc">/</span> n[combs[<span class="dv">2</span>,x]])<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="co"># numerator dof</span></span>
<span id="cb489-21"><a href="comparing-multiple-means.html#cb489-21" aria-hidden="true" tabindex="-1"></a>      ((std[combs[<span class="dv">1</span>,x]] <span class="sc">/</span> n[combs[<span class="dv">1</span>,x]])<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (n[combs[<span class="dv">1</span>,x]] <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co"># Part 1 of denominator dof</span></span>
<span id="cb489-22"><a href="comparing-multiple-means.html#cb489-22" aria-hidden="true" tabindex="-1"></a>         (std[combs[<span class="dv">2</span>,x]] <span class="sc">/</span> n[combs[<span class="dv">2</span>,x]])<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (n[combs[<span class="dv">2</span>,x]] <span class="sc">-</span> <span class="dv">1</span>)) <span class="co"># Part 2 of denominator dof</span></span>
<span id="cb489-23"><a href="comparing-multiple-means.html#cb489-23" aria-hidden="true" tabindex="-1"></a>    <span class="co"># p-values</span></span>
<span id="cb489-24"><a href="comparing-multiple-means.html#cb489-24" aria-hidden="true" tabindex="-1"></a>    p <span class="ot">&lt;-</span> <span class="fu">ptukey</span>(t <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">2</span>), groups, df, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb489-25"><a href="comparing-multiple-means.html#cb489-25" aria-hidden="true" tabindex="-1"></a>    <span class="co"># sigma standard error</span></span>
<span id="cb489-26"><a href="comparing-multiple-means.html#cb489-26" aria-hidden="true" tabindex="-1"></a>    se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fl">0.5</span> <span class="sc">*</span> (std[combs[<span class="dv">1</span>,x]] <span class="sc">/</span> n[combs[<span class="dv">1</span>,x]] <span class="sc">+</span> std[combs[<span class="dv">2</span>,x]] <span class="sc">/</span> n[combs[<span class="dv">2</span>,x]]))</span>
<span id="cb489-27"><a href="comparing-multiple-means.html#cb489-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Upper Confidence Limit</span></span>
<span id="cb489-28"><a href="comparing-multiple-means.html#cb489-28" aria-hidden="true" tabindex="-1"></a>    upper.conf <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(combs), <span class="cf">function</span>(x) {</span>
<span id="cb489-29"><a href="comparing-multiple-means.html#cb489-29" aria-hidden="true" tabindex="-1"></a>      mean.diff <span class="sc">+</span> <span class="fu">qtukey</span>(<span class="at">p =</span> <span class="fl">0.95</span>, <span class="at">nmeans =</span> groups, <span class="at">df =</span> df) <span class="sc">*</span> se</span>
<span id="cb489-30"><a href="comparing-multiple-means.html#cb489-30" aria-hidden="true" tabindex="-1"></a>    })[[<span class="dv">1</span>]]</span>
<span id="cb489-31"><a href="comparing-multiple-means.html#cb489-31" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Lower Confidence Limit</span></span>
<span id="cb489-32"><a href="comparing-multiple-means.html#cb489-32" aria-hidden="true" tabindex="-1"></a>    lower.conf <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(combs), <span class="cf">function</span>(x) {</span>
<span id="cb489-33"><a href="comparing-multiple-means.html#cb489-33" aria-hidden="true" tabindex="-1"></a>      mean.diff <span class="sc">-</span> <span class="fu">qtukey</span>(<span class="at">p =</span> <span class="fl">0.95</span>, <span class="at">nmeans =</span> groups, <span class="at">df =</span> df) <span class="sc">*</span> se</span>
<span id="cb489-34"><a href="comparing-multiple-means.html#cb489-34" aria-hidden="true" tabindex="-1"></a>    })[[<span class="dv">1</span>]]</span>
<span id="cb489-35"><a href="comparing-multiple-means.html#cb489-35" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Group Combinations</span></span>
<span id="cb489-36"><a href="comparing-multiple-means.html#cb489-36" aria-hidden="true" tabindex="-1"></a>    grp.comb <span class="ot">&lt;-</span> <span class="fu">paste</span>(combs[<span class="dv">1</span>,x], <span class="st">&#39;:&#39;</span>, combs[<span class="dv">2</span>,x])</span>
<span id="cb489-37"><a href="comparing-multiple-means.html#cb489-37" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Collect all statistics into list</span></span>
<span id="cb489-38"><a href="comparing-multiple-means.html#cb489-38" aria-hidden="true" tabindex="-1"></a>    stats <span class="ot">&lt;-</span> <span class="fu">list</span>(grp.comb, mean.diff, se, t, df, p, upper.conf, lower.conf)</span>
<span id="cb489-39"><a href="comparing-multiple-means.html#cb489-39" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb489-40"><a href="comparing-multiple-means.html#cb489-40" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb489-41"><a href="comparing-multiple-means.html#cb489-41" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Unlist statistics collected earlier</span></span>
<span id="cb489-42"><a href="comparing-multiple-means.html#cb489-42" aria-hidden="true" tabindex="-1"></a>  stats.unlisted <span class="ot">&lt;-</span> <span class="fu">lapply</span>(statistics, <span class="cf">function</span>(x) {</span>
<span id="cb489-43"><a href="comparing-multiple-means.html#cb489-43" aria-hidden="true" tabindex="-1"></a>    <span class="fu">unlist</span>(x)</span>
<span id="cb489-44"><a href="comparing-multiple-means.html#cb489-44" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb489-45"><a href="comparing-multiple-means.html#cb489-45" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb489-46"><a href="comparing-multiple-means.html#cb489-46" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create dataframe from flattened list</span></span>
<span id="cb489-47"><a href="comparing-multiple-means.html#cb489-47" aria-hidden="true" tabindex="-1"></a>  results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">matrix</span>(<span class="fu">unlist</span>(stats.unlisted), <span class="at">nrow =</span> <span class="fu">length</span>(stats.unlisted), <span class="at">byrow=</span><span class="cn">TRUE</span>))</span>
<span id="cb489-48"><a href="comparing-multiple-means.html#cb489-48" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Select columns set as factors that should be numeric and change with as.numeric</span></span>
<span id="cb489-49"><a href="comparing-multiple-means.html#cb489-49" aria-hidden="true" tabindex="-1"></a>  results[<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span><span class="sc">:</span><span class="fu">ncol</span>(results))] <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">as.numeric</span>(<span class="fu">as.matrix</span>(results[<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span><span class="sc">:</span><span class="fu">ncol</span>(results))])), <span class="at">digits =</span> <span class="dv">3</span>)</span>
<span id="cb489-50"><a href="comparing-multiple-means.html#cb489-50" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Rename data frame columns</span></span>
<span id="cb489-51"><a href="comparing-multiple-means.html#cb489-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">colnames</span>(results) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&#39;groups&#39;</span>, <span class="st">&#39;Mean Difference&#39;</span>, <span class="st">&#39;Standard Error&#39;</span>, <span class="st">&#39;t&#39;</span>, <span class="st">&#39;df&#39;</span>, <span class="st">&#39;p&#39;</span>, <span class="st">&#39;upper limit&#39;</span>, <span class="st">&#39;lower limit&#39;</span>)</span>
<span id="cb489-52"><a href="comparing-multiple-means.html#cb489-52" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(results)</span>
<span id="cb489-53"><a href="comparing-multiple-means.html#cb489-53" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>After defining the function, we can use it. If you decide to use the Games-Howell function, you can simply copy-and-paste it. Since this function is open-source code, citation is not necessary.</p>
<div class="sourceCode" id="cb490"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb490-1"><a href="comparing-multiple-means.html#cb490-1" aria-hidden="true" tabindex="-1"></a><span class="fu">games.howell</span>(<span class="at">grp =</span> dat<span class="fl">.1952</span><span class="sc">$</span>Income_Level_1952,  <span class="co"># Groups, the categorical variable</span></span>
<span id="cb490-2"><a href="comparing-multiple-means.html#cb490-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">obs =</span> dat<span class="fl">.1952</span><span class="sc">$</span>lifeExp)            <span class="co"># Observations, the continuous variable</span></span></code></pre></div>
<pre><code>##                     groups Mean Difference Standard Error      t     df    p
## 1 Low Middle : High Middle           8.807          1.444  4.311 58.295 0.00
## 2        Low Middle : High          20.169          1.440  9.905 58.438 0.00
## 3         Low Middle : Low          -4.207          1.043  2.852 58.143 0.03
## 4       High Middle : High          11.362          1.651  4.866 63.999 0.00
## 5        High Middle : Low         -13.014          1.319  6.974 48.168 0.00
## 6               High : Low         -24.376          1.315 13.113 48.302 0.00
##   upper limit lower limit
## 1      14.210       3.404
## 2      25.555      14.784
## 3      -0.305      -8.109
## 4      17.522       5.203
## 5      -8.048     -17.980
## 6     -19.430     -29.323</code></pre>
</div>
<div id="two-way-anova" class="section level3" number="8.3.3">
<h3><span class="header-section-number">8.3.3</span> Two-way ANOVA</h3>
<p>We can also look at 2 independent categorical variables together with a two-way ANOVA. This is as easy as calling <code>aov()</code> with an additional variable on the right side of the <code>y ~ x</code> formula. For example, we can take a look at both <code>Income_Level_2007</code> and <code>demLevel</code> as explanatory variables to the response variable <code>lifeExp</code>.</p>
<div class="sourceCode" id="cb492"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb492-1"><a href="comparing-multiple-means.html#cb492-1" aria-hidden="true" tabindex="-1"></a>two_way_plus <span class="ot">&lt;-</span> <span class="fu">aov</span>(lifeExp <span class="sc">~</span> Income_Level_2007 <span class="sc">+</span> demLev, <span class="at">data =</span> dat<span class="fl">.2007</span>)</span>
<span id="cb492-2"><a href="comparing-multiple-means.html#cb492-2" aria-hidden="true" tabindex="-1"></a>two_way_star <span class="ot">&lt;-</span> <span class="fu">aov</span>(lifeExp <span class="sc">~</span> Income_Level_2007 <span class="sc">*</span> demLev, <span class="at">data =</span> dat<span class="fl">.2007</span>)</span></code></pre></div>
<p>You might have noticed that I used <code>+</code> to connect the 2 explanatory variables in the first line and <code>*</code> for the second line. How are they different? Take a look at the results below.</p>
<div class="sourceCode" id="cb493"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb493-1"><a href="comparing-multiple-means.html#cb493-1" aria-hidden="true" tabindex="-1"></a>two_way_plus</span></code></pre></div>
<pre><code>## Call:
##    aov(formula = lifeExp ~ Income_Level_2007 + demLev, data = dat.2007)
## 
## Terms:
##                 Income_Level_2007    demLev Residuals
## Sum of Squares          12199.101   437.708  6446.792
## Deg. of Freedom                 3         2       126
## 
## Residual standard error: 7.152973
## Estimated effects may be unbalanced</code></pre>
<div class="sourceCode" id="cb495"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb495-1"><a href="comparing-multiple-means.html#cb495-1" aria-hidden="true" tabindex="-1"></a>two_way_star</span></code></pre></div>
<pre><code>## Call:
##    aov(formula = lifeExp ~ Income_Level_2007 * demLev, data = dat.2007)
## 
## Terms:
##                 Income_Level_2007    demLev Income_Level_2007:demLev Residuals
## Sum of Squares          12199.101   437.708                  662.338  5784.454
## Deg. of Freedom                 3         2                        6       120
## 
## Residual standard error: 6.942895
## Estimated effects may be unbalanced</code></pre>
<div class="sourceCode" id="cb497"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb497-1"><a href="comparing-multiple-means.html#cb497-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(two_way_plus)</span></code></pre></div>
<pre><code>##                    Df Sum Sq Mean Sq F value Pr(&gt;F)    
## Income_Level_2007   3  12199    4066  79.476 &lt;2e-16 ***
## demLev              2    438     219   4.277 0.0159 *  
## Residuals         126   6447      51                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb499"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb499-1"><a href="comparing-multiple-means.html#cb499-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(two_way_star)</span></code></pre></div>
<pre><code>##                           Df Sum Sq Mean Sq F value Pr(&gt;F)    
## Income_Level_2007          3  12199    4066   84.36 &lt;2e-16 ***
## demLev                     2    438     219    4.54 0.0126 *  
## Income_Level_2007:demLev   6    662     110    2.29 0.0396 *  
## Residuals                120   5784      48                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>In the test with <code>*</code>, there is one more term <code>Income_Level_2007:demLev</code>. This is the interaction between the two variables. In this case, the interaction of of the two variables also contribute significantly to the difference in <code>lifeExp</code>. For the purposes of the Youreka program, it doesn’t matter which method you use.</p>
</div>
</div>
<div id="linear-regression" class="section level2" number="8.4">
<h2><span class="header-section-number">8.4</span> Linear regression</h2>
<div id="basic-concepts" class="section level3" number="8.4.1">
<h3><span class="header-section-number">8.4.1</span> Basic concepts</h3>
<p>We have discussed extensively for the scenario where you have a continuous variable and a categorical variable. Now we will talk about what you do if both variables are continuous.</p>
<p>For this final section, we will test for a relationship between life expectancy and per capita <a href="https://en.wikipedia.org/wiki/Gross_domestic_product">gross domestic product</a> (GDP).</p>
<p>As we did for the ANOVA analyses, it is usually a good idea to visually inspect the data when possible. Here we can use the <code>plot</code> function to create a scatterplot of the two columns of interest, <code>lifeExp</code> and <code>gdpPercap</code>.</p>
<div class="sourceCode" id="cb501"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb501-1"><a href="comparing-multiple-means.html#cb501-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> dat<span class="fl">.2007</span>, <span class="fu">aes</span>(<span class="at">x =</span> gdpPercap, <span class="at">y =</span> lifeExp)) <span class="sc">+</span></span>
<span id="cb501-2"><a href="comparing-multiple-means.html#cb501-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-213-1.png" width="672" /></p>
<p>We can see immediately that this is unlikely a linear relationship. In this case, we will need to log-transform the GDP data to obtain a linear relationship.</p>
<div class="sourceCode" id="cb502"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb502-1"><a href="comparing-multiple-means.html#cb502-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> dat<span class="fl">.2007</span>, <span class="fu">aes</span>(<span class="at">x =</span> gdpPercap, <span class="at">y =</span> lifeExp)) <span class="sc">+</span></span>
<span id="cb502-2"><a href="comparing-multiple-means.html#cb502-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb502-3"><a href="comparing-multiple-means.html#cb502-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-214-1.png" width="672" /></p>
<p>Now that the data are properly transformed, we can create the linear model for the predictability of life expectancy based on gross domestic product. Before we do that let’s make it clear:</p>
<ol style="list-style-type: decimal">
<li><p>From the scatter plot we can identify a positive relationship – when log(GDP per capita) increases, the life expectancy also tends to be higher. The tendency of one variable going up or down <em>linearly</em> with the increase of another variable is called “correlation.” The more consistent the points are with a LINEAR trend, the higher the closer the correlation is to -1 (for negative relationships) or +1 (for positive relationships).</p></li>
<li><p>How fast one variable increases or decreases with the increase of another variable can be described by the slope of the fitting line. To estimate the slope, we need a linear model.</p></li>
<li><p>We can only discuss strength of correlation with these linear regression, but NOT the causation. That is, correlation does NOT imply causation.</p></li>
</ol>
<p>We can plot the linear model easily:</p>
<div class="sourceCode" id="cb503"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb503-1"><a href="comparing-multiple-means.html#cb503-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> dat<span class="fl">.2007</span>, <span class="fu">aes</span>(<span class="at">x =</span> gdpPercap, <span class="at">y =</span> lifeExp)) <span class="sc">+</span></span>
<span id="cb503-2"><a href="comparing-multiple-means.html#cb503-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb503-3"><a href="comparing-multiple-means.html#cb503-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>() <span class="sc">+</span></span>
<span id="cb503-4"><a href="comparing-multiple-means.html#cb503-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>)  <span class="co"># lm = linear model</span></span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="_main_files/figure-html/lm-method-1.png" width="672" /></p>
<p>To get rid of the confidence band around the line, pass <code>se = FALSE</code> into <code>geom_smooth()</code>.</p>
<div class="sourceCode" id="cb505"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb505-1"><a href="comparing-multiple-means.html#cb505-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> dat<span class="fl">.2007</span>, <span class="fu">aes</span>(<span class="at">x =</span> gdpPercap, <span class="at">y =</span> lifeExp)) <span class="sc">+</span></span>
<span id="cb505-2"><a href="comparing-multiple-means.html#cb505-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb505-3"><a href="comparing-multiple-means.html#cb505-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>() <span class="sc">+</span></span>
<span id="cb505-4"><a href="comparing-multiple-means.html#cb505-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)  <span class="co"># lm = linear model</span></span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="_main_files/figure-html/lm-method-sefalse-1.png" width="672" /></p>
<p>You can also customize the colour and thickness of the line. As always, use the <code>?</code> operator to get the full documentation.</p>
</div>
<div id="pearson-correlation" class="section level3" number="8.4.2">
<h3><span class="header-section-number">8.4.2</span> Pearson correlation</h3>
<p>Let’s look at the correlation. For normal distributed data, we calculate the Pearson correlation for the log-transformed variable.</p>
<div class="sourceCode" id="cb507"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb507-1"><a href="comparing-multiple-means.html#cb507-1" aria-hidden="true" tabindex="-1"></a>dat<span class="fl">.2007</span><span class="sc">$</span>log_GDP <span class="ot">&lt;-</span> <span class="fu">log</span>(dat<span class="fl">.2007</span><span class="sc">$</span>gdpPercap)   <span class="co"># add new variable</span></span>
<span id="cb507-2"><a href="comparing-multiple-means.html#cb507-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(<span class="at">x =</span> dat<span class="fl">.2007</span><span class="sc">$</span>log_GDP, <span class="at">y =</span> dat<span class="fl">.2007</span><span class="sc">$</span>lifeExp, <span class="at">method =</span> <span class="st">&quot;pearson&quot;</span>)  <span class="co"># method options: pearson, kendall, spearman</span></span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  dat.2007$log_GDP and dat.2007$lifeExp
## t = 15.626, df = 130, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.7389427 0.8599823
## sample estimates:
##       cor 
## 0.8078163</code></pre>
<p>The p-value suggests the correlation is significant. The correlation coefficient of 0.8 suggests a positive correation (y increases as x increases). In case you see a negative value, the correlation if negative (one variable going up while the other going down).</p>
<p>Next we can construct a linear model.</p>
<div class="sourceCode" id="cb509"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb509-1"><a href="comparing-multiple-means.html#cb509-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run a linear model</span></span>
<span id="cb509-2"><a href="comparing-multiple-means.html#cb509-2" aria-hidden="true" tabindex="-1"></a>lifeExp.v.gdp <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> lifeExp <span class="sc">~</span> log_GDP, <span class="at">data =</span> dat<span class="fl">.2007</span>)</span>
<span id="cb509-3"><a href="comparing-multiple-means.html#cb509-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Investigate results of the model</span></span>
<span id="cb509-4"><a href="comparing-multiple-means.html#cb509-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lifeExp.v.gdp)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = lifeExp ~ log_GDP, data = dat.2007)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -25.692  -2.711   1.441   4.652  13.362 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   4.7951     4.0045   1.197    0.233    
## log_GDP       7.1909     0.4602  15.626   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.142 on 130 degrees of freedom
## Multiple R-squared:  0.6526, Adjusted R-squared:  0.6499 
## F-statistic: 244.2 on 1 and 130 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The linear equation is: <span class="math inline">\(\text{lifeExp} = (7.1909 \pm 0.4602) \times \text{log_GDP} + (4.7951 \pm 4.0045)\)</span>. Also notice that the correlation coefficient is <span class="math inline">\(R^2 = 0.6526 \Rightarrow R = \sqrt{0.6526} = 0.8078\)</span>, the same value returned by <code>cor.test()</code>.</p>
<p>For our question, the relationship between life expectancy and GDP, focus on the <em>coefficients</em> section, specifically the line for <code>log_GDP</code>.</p>
<p>First of all, there <em>is</em> a significant relationship between these two variables (p &lt; 2 x 10<sup>-16</sup>, or, as R reports in the <code>Pr&gt;(|t|)</code> column, p &lt; 2e-16). The <code>Estimate</code> column of the results lists a value of <code>lifeExp.v.gdp$coefficients['log_GDP']</code>. For every 10-fold increase in per capita GDP (remember we log<sub>10</sub>-transformed GDP), life expectancy increases by almost 7 years.</p>
<p>The linear model relies assumes that your data is normally distributed. We can generate a diagnostic plot in the same way as one-way ANOVA.</p>
<div class="sourceCode" id="cb511"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb511-1"><a href="comparing-multiple-means.html#cb511-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lifeExp.v.gdp)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-216-1.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-216-2.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-216-3.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-216-4.png" width="672" /></p>
<p>Q-Q plot suggested this data deviates from normality. Let’s also take a look at the residues of the linear model:</p>
<div class="sourceCode" id="cb512"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb512-1"><a href="comparing-multiple-means.html#cb512-1" aria-hidden="true" tabindex="-1"></a>residuals_lm <span class="ot">&lt;-</span> <span class="fu">residuals</span>(<span class="at">object =</span> lifeExp.v.gdp)</span>
<span id="cb512-2"><a href="comparing-multiple-means.html#cb512-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="at">x =</span> residuals_lm)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuals_lm
## W = 0.89588, p-value = 3.911e-08</code></pre>
<p>Indeed, Shapiro test also suggests the data deviates from normality. In this case, we should use the Spearman (or Kendall) correlation.</p>
</div>
<div id="spearman-correlation" class="section level3" number="8.4.3">
<h3><span class="header-section-number">8.4.3</span> Spearman correlation</h3>
<p>If your variables are not normally distributed, you can use the non-parametric Spearman correlation as alternative. Instead of Pearson’s R, the Spearman test outputs rho (<span class="math inline">\(\rho\)</span>),</p>
<div class="sourceCode" id="cb514"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb514-1"><a href="comparing-multiple-means.html#cb514-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(dat<span class="fl">.2007</span><span class="sc">$</span>lifeExp, dat<span class="fl">.2007</span><span class="sc">$</span>log_GDP, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  dat.2007$lifeExp and dat.2007$log_GDP
## S = 57612, p-value &lt; 2.2e-16
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##       rho 
## 0.8496971</code></pre>

</div>
</div>
</div>



            </section>

          </div>
        </div>
      </div>
<a href="basic-statistical-tests.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="data-visualization-basics.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
